// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToPath() {
  return window['go']['gui']['App']['AddToPath']();
}

export function CancelCompress() {
  return window['go']['gui']['App']['CancelCompress']();
}

export function CancelGifExport() {
  return window['go']['gui']['App']['CancelGifExport']();
}

export function ClearDebugLogs() {
  return window['go']['gui']['App']['ClearDebugLogs']();
}

export function DetectFFmpeg() {
  return window['go']['gui']['App']['DetectFFmpeg']();
}

export function DetectGPUEncoder() {
  return window['go']['gui']['App']['DetectGPUEncoder']();
}

export function DownloadFFmpeg() {
  return window['go']['gui']['App']['DownloadFFmpeg']();
}

export function GetDebugLogs() {
  return window['go']['gui']['App']['GetDebugLogs']();
}

export function GetGifFormats() {
  return window['go']['gui']['App']['GetGifFormats']();
}

export function GetGifTiers() {
  return window['go']['gui']['App']['GetGifTiers']();
}

export function GetInitialFiles() {
  return window['go']['gui']['App']['GetInitialFiles']();
}

export function GetIntegrationStatus() {
  return window['go']['gui']['App']['GetIntegrationStatus']();
}

export function GetLanguage() {
  return window['go']['gui']['App']['GetLanguage']();
}

export function GetPresets() {
  return window['go']['gui']['App']['GetPresets']();
}

export function GetVersion() {
  return window['go']['gui']['App']['GetVersion']();
}

export function InstallContextMenu() {
  return window['go']['gui']['App']['InstallContextMenu']();
}

export function InstallDesktopShortcut() {
  return window['go']['gui']['App']['InstallDesktopShortcut']();
}

export function InstallSendTo() {
  return window['go']['gui']['App']['InstallSendTo']();
}

export function InstallStartMenuShortcut() {
  return window['go']['gui']['App']['InstallStartMenuShortcut']();
}

export function OpenDebugLogFile() {
  return window['go']['gui']['App']['OpenDebugLogFile']();
}

export function OpenFolder(arg1) {
  return window['go']['gui']['App']['OpenFolder'](arg1);
}

export function RemoveFromPath() {
  return window['go']['gui']['App']['RemoveFromPath']();
}

export function SelectFiles() {
  return window['go']['gui']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['gui']['App']['SelectFolder']();
}

export function SetDebugMode(arg1) {
  return window['go']['gui']['App']['SetDebugMode'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['gui']['App']['SetLanguage'](arg1);
}

export function StartCompress(arg1) {
  return window['go']['gui']['App']['StartCompress'](arg1);
}

export function StartGifExport(arg1) {
  return window['go']['gui']['App']['StartGifExport'](arg1);
}

export function UninstallContextMenu() {
  return window['go']['gui']['App']['UninstallContextMenu']();
}

export function UninstallDesktopShortcut() {
  return window['go']['gui']['App']['UninstallDesktopShortcut']();
}

export function UninstallSendTo() {
  return window['go']['gui']['App']['UninstallSendTo']();
}

export function UninstallStartMenuShortcut() {
  return window['go']['gui']['App']['UninstallStartMenuShortcut']();
}
