// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToPath() {
  return window['go']['main']['App']['AddToPath']();
}

export function DetectFFmpeg() {
  return window['go']['main']['App']['DetectFFmpeg']();
}

export function DetectGPUEncoder() {
  return window['go']['main']['App']['DetectGPUEncoder']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function InstallSendTo() {
  return window['go']['main']['App']['InstallSendTo']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RemoveFromPath() {
  return window['go']['main']['App']['RemoveFromPath']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function StartCompress(arg1) {
  return window['go']['main']['App']['StartCompress'](arg1);
}

export function UninstallSendTo() {
  return window['go']['main']['App']['UninstallSendTo']();
}
