// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';

export function AddToPath():Promise<boolean>;

export function CancelCompress():Promise<void>;

export function ClearDebugLogs():Promise<void>;

export function DetectFFmpeg():Promise<string>;

export function DetectGPUEncoder():Promise<string>;

export function DownloadFFmpeg():Promise<void>;

export function GetDebugLogs():Promise<string>;

export function GetInitialFiles():Promise<Array<string>>;

export function GetIntegrationStatus():Promise<Record<string, boolean>>;

export function GetPresets():Promise<Array<main.PresetInfo>>;

export function GetVersion():Promise<string>;

export function InstallContextMenu():Promise<void>;

export function InstallDesktopShortcut():Promise<void>;

export function InstallSendTo():Promise<string>;

export function InstallStartMenuShortcut():Promise<void>;

export function OpenDebugLogFile():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveFromPath():Promise<boolean>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function StartCompress(arg1:engine.JobRequest):Promise<Array<engine.JobReport>>;

export function UninstallContextMenu():Promise<void>;

export function UninstallDesktopShortcut():Promise<void>;

export function UninstallSendTo():Promise<void>;

export function UninstallStartMenuShortcut():Promise<void>;
