// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';

export function AddToPath():Promise<boolean>;

export function DetectFFmpeg():Promise<string>;

export function DetectGPUEncoder():Promise<string>;

export function GetPresets():Promise<Array<main.PresetInfo>>;

export function InstallSendTo():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveFromPath():Promise<boolean>;

export function SelectFiles():Promise<Array<string>>;

export function StartCompress(arg1:engine.JobRequest):Promise<Array<engine.JobReport>>;

export function UninstallSendTo():Promise<void>;
